#数据库
database:
  mysql:
    dsn: root:root@tcp(127.0.0.1:3306)/dev_test?charset=utf8mb4&parseTime=True&loc=Local
    tablePrefix: t_
  redis:
    addr: 127.0.0.1:6379
    password:
    db: 0
#应用
app:
  port: :8080
log:
  filename: ./_runtime/logs/access.log
  maxSize: 200
  maxBackup: 200
  maxAge: 100
